CREATE TABLE TB_PESSOA (
    ID_PESSOA BIGSERIAL NOT NULL PRIMARY KEY,
    NM_PESSOA_NOME VARCHAR(150) NOT NULL,
	NM_PESSOA_SOBRENOME VARCHAR(150) NOT NULL,
    NR_CPF VARCHAR(14) NOT NULL UNIQUE,
    TX_EMAIL VARCHAR(150) NOT NULL UNIQUE,
    TP_TITULACAO VARCHAR(50) NOT NULL,
    ST_ATIVO BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE TB_TELEFONE (
    ID_TELEFONE BIGSERIAL NOT NULL PRIMARY KEY,
    NR_DDD INTEGER NOT NULL,
    NR_TELEFONE VARCHAR(15) NOT NULL,
    ID_PESSOA BIGINT NOT NULL REFERENCES TB_PESSOA(ID_PESSOA)
);

CREATE TABLE TB_FINANCIADOR (
    ID_FINANCIADOR BIGSERIAL NOT NULL PRIMARY KEY,
    NM_FINANCIADOR VARCHAR(255) NOT NULL,
    TP_FINANCIADOR VARCHAR(50),
    NR_CNPJ VARCHAR(18) UNIQUE,
    TX_EMAIL_CONTATO VARCHAR(150)
);

CREATE TABLE TB_PUBLICACAO (
    ID_PUBLICACAO BIGSERIAL NOT NULL PRIMARY KEY,
    NM_TITULO_PUBLICACAO VARCHAR(255) NOT NULL,
    NR_ANO INTEGER NOT NULL,
    TP_PUBLICACAO VARCHAR(50)
);

CREATE TABLE TB_PROJETO (
    ID_PROJETO BIGSERIAL NOT NULL PRIMARY KEY,
    NM_TITULO_PROJETO VARCHAR(255) NOT NULL,
    TX_DESCRICAO TEXT,
    DT_INICIO DATE NOT NULL,
    DT_FIM DATE,
    VL_ORCAMENTO_TOTAL NUMERIC(15, 2),
    ID_COORDENADOR BIGINT NOT NULL REFERENCES TB_PESSOA(ID_PESSOA)
);

CREATE TABLE TB_CONTRATO (
    ID_CONTRATO BIGSERIAL NOT NULL PRIMARY KEY,
    NR_CONTRATO VARCHAR(50) NOT NULL UNIQUE,
    TP_CONTRATO VARCHAR(50) NOT NULL,
    VL_CONTRATO_TOTAL NUMERIC(15, 2) NOT NULL,
    DT_INICIO DATE NOT NULL,
    DT_FIM DATE,
    ID_PROJETO BIGINT NOT NULL REFERENCES TB_PROJETO(ID_PROJETO),
    ID_FINANCIADOR BIGINT NOT NULL REFERENCES TB_FINANCIADOR(ID_FINANCIADOR)
);

CREATE TABLE TB_BOLSA (
    ID_BOLSA BIGSERIAL NOT NULL PRIMARY KEY,
    TP_BOLSA VARCHAR(50) NOT NULL,
    VL_BOLSA_MENSAL NUMERIC(10, 2) NOT NULL,
    DT_INICIO DATE NOT NULL,
    DT_FIM DATE,
    ID_CONTRATO BIGINT NOT NULL REFERENCES TB_CONTRATO(ID_CONTRATO),
    ID_BOLSISTA BIGINT NOT NULL UNIQUE REFERENCES TB_PESSOA(ID_PESSOA)
);

CREATE TABLE TB_EQUIPAMENTO (
    ID_EQUIPAMENTO BIGSERIAL NOT NULL PRIMARY KEY,
    NM_EQUIPAMENTO VARCHAR(100) NOT NULL,
    NR_SERIE VARCHAR(50) UNIQUE,
    DT_AQUISICAO DATE,
    VL_COMPRA NUMERIC(15, 2),
    ST_STATUS VARCHAR(20) DEFAULT 'ATIVO' NOT NULL,
    ID_PROJETO BIGINT NOT NULL REFERENCES TB_PROJETO(ID_PROJETO),
    ID_RESPONSAVEL BIGINT REFERENCES TB_PESSOA(ID_PESSOA)
);

CREATE TABLE TB_RELATORIO (
    ID_RELATORIO BIGSERIAL NOT NULL PRIMARY KEY,
    TP_RELATORIO VARCHAR(50) NOT NULL,
    DT_ENTREGA DATE NOT NULL,
    TX_DESCRICAO TEXT,
    ID_PROJETO BIGINT NOT NULL REFERENCES TB_PROJETO(ID_PROJETO),
    ID_AUTOR BIGINT NOT NULL REFERENCES TB_PESSOA(ID_PESSOA)
);

CREATE TABLE TR_TRABALHA_EM (
    ID_PESSOA BIGINT NOT NULL REFERENCES TB_PESSOA(ID_PESSOA),
    ID_PROJETO BIGINT NOT NULL REFERENCES TB_PROJETO(ID_PROJETO),
    DT_INICIO_PARTICIPACAO DATE NOT NULL,
    DT_FIM_PARTICIPACAO DATE,
    DS_FUNCAO VARCHAR(100),
    PRIMARY KEY (ID_PESSOA, ID_PROJETO, DT_INICIO_PARTICIPACAO)
);

CREATE TABLE TR_AUTORIA (
    ID_PESSOA BIGINT NOT NULL REFERENCES TB_PESSOA(ID_PESSOA),
    ID_PUBLICACAO BIGINT NOT NULL REFERENCES TB_PUBLICACAO(ID_PUBLICACAO),
    NR_ORDEM_AUTORIA INTEGER NOT NULL,
    PRIMARY KEY (ID_PESSOA, ID_PUBLICACAO)
);

CREATE TABLE TR_GERA_PUBLICACAO ( 
    ID_PROJETO BIGINT NOT NULL REFERENCES TB_PROJETO(ID_PROJETO),
    ID_PUBLICACAO BIGINT NOT NULL REFERENCES TB_PUBLICACAO(ID_PUBLICACAO),
    PRIMARY KEY (ID_PROJETO, ID_PUBLICACAO)
);

--COMMIT;