

/* SEÇÃO 1: CONSULTAS INTERMEDIÁRIAS */

/* [INT-01] Produção bibliográfica por pesquisador */
-- Requisito: [REQ-01] Gestão de Produtividade.
-- Justificativa: Identificar o volume de produção de cada pesquisador para avaliações de desempenho.
-- Tabelas: TB_PESSOA, TR_AUTORIA, TB_PUBLICACAO (3)
-- Elementos: JOIN, GROUP BY, COUNT (3)
SELECT
    P.NM_PESSOA_NOME,
    P.NM_PESSOA_SOBRENOME,
    COUNT(PUB.ID_PUBLICACAO) AS TOTAL_PUBLICACOES
FROM TB_PESSOA P
INNER JOIN TR_AUTORIA A ON P.ID_PESSOA = A.ID_PESSOA
INNER JOIN TB_PUBLICACAO PUB ON A.ID_PUBLICACAO = PUB.ID_PUBLICACAO
GROUP BY P.ID_PESSOA, P.NM_PESSOA_NOME, P.NM_PESSOA_SOBRENOME
ORDER BY TOTAL_PUBLICACOES DESC;

/* [INT-02] Custo total de equipamentos por projeto */
-- Requisito: [REQ-03] Gestão Financeira.
-- Justificativa: Auditoria de gastos com infraestrutura por projeto.
SELECT
    PROJ.NM_TITULO_PROJETO,
    COORD.NM_PESSOA_NOME AS NM_COORDENADOR,
    SUM(EQ.VL_COMPRA) AS TOTAL_GASTO_EQUIPAMENTOS
FROM TB_PROJETO PROJ
INNER JOIN TB_EQUIPAMENTO EQ ON PROJ.ID_PROJETO = EQ.ID_PROJETO
INNER JOIN TB_PESSOA COORD ON PROJ.ID_COORDENADOR = COORD.ID_PESSOA
GROUP BY PROJ.ID_PROJETO, PROJ.NM_TITULO_PROJETO, COORD.NM_PESSOA_NOME
HAVING SUM(EQ.VL_COMPRA) > 0
ORDER BY TOTAL_GASTO_EQUIPAMENTOS DESC;

/* [INT-03] Contagem de bolsistas por tipo em cada contrato */
-- Requisito: [REQ-03] Gestão Financeira / [REQ-02] Gestão de Recursos Humanos.
-- Justificativa: Saber qual tipo de bolsa é mais predominante em cada contrato de financiamento.
-- Tabelas: TB_CONTRATO, TB_BOLSA, TB_FINANCIADOR (3)
-- Elementos: JOIN, GROUP BY, COUNT (3)
SELECT
    F.NM_FINANCIADOR,
    C.NR_CONTRATO,
    B.TP_BOLSA,
    COUNT(B.ID_BOLSA) AS QTD_BOLSAS
FROM TB_FINANCIADOR F
INNER JOIN TB_CONTRATO C ON F.ID_FINANCIADOR = C.ID_FINANCIADOR
INNER JOIN TB_BOLSA B ON C.ID_CONTRATO = B.ID_CONTRATO
GROUP BY F.NM_FINANCIADOR, C.NR_CONTRATO, B.TP_BOLSA
ORDER BY F.NM_FINANCIADOR, C.NR_CONTRATO;

/* [INT-04] Projetos e número de membros ativos na equipe */
-- Requisito: [REQ-02] Gestão de Recursos Humanos.
-- Justificativa: Monitorar o tamanho atual das equipes dos projetos.
-- Tabelas: TB_PROJETO, TR_TRABALHA_EM, TB_PESSOA (3)
-- Elementos: JOIN, GROUP BY, COUNT (3)
SELECT
    PROJ.NM_TITULO_PROJETO,
    COUNT(T.ID_PESSOA) AS MEMBROS_ATIVOS
FROM TB_PROJETO PROJ
INNER JOIN TR_TRABALHA_EM T ON PROJ.ID_PROJETO = T.ID_PROJETO
INNER JOIN TB_PESSOA P ON T.ID_PESSOA = P.ID_PESSOA
WHERE T.DT_FIM_PARTICIPACAO IS NULL -- Apenas membros ativos
GROUP BY PROJ.ID_PROJETO, PROJ.NM_TITULO_PROJETO
ORDER BY MEMBROS_ATIVOS DESC;

/* [INT-05] Relatórios entregues por ano e autor */
-- Requisito: [REQ-01] Gestão de Produtividade.
-- Justificativa: Controle de entregas técnicas obrigatórias por pesquisador.

SELECT
    P.NM_PESSOA_NOME,
    EXTRACT(YEAR FROM R.DT_ENTREGA) AS ANO_ENTREGA,
    COUNT(R.ID_RELATORIO) AS TOTAL_RELATORIOS
FROM TB_PESSOA P
INNER JOIN TB_RELATORIO R ON P.ID_PESSOA = R.ID_AUTOR
INNER JOIN TB_PROJETO PROJ ON R.ID_PROJETO = PROJ.ID_PROJETO
GROUP BY P.NM_PESSOA_NOME, ANO_ENTREGA
ORDER BY P.NM_PESSOA_NOME, ANO_ENTREGA DESC;

/* [INT-06] Média de valores de contrato por financiador */
-- Requisito: [REQ-03] Gestão Financeira.
SELECT
    F.NM_FINANCIADOR,
    COUNT(C.ID_CONTRATO) AS QTD_CONTRATOS,
    AVG(C.VL_CONTRATO_TOTAL)::NUMERIC(15,2) AS MEDIA_VALOR_CONTRATO
FROM TB_FINANCIADOR F
INNER JOIN TB_CONTRATO C ON F.ID_FINANCIADOR = C.ID_FINANCIADOR
INNER JOIN TB_PROJETO P ON C.ID_PROJETO = P.ID_PROJETO
GROUP BY F.ID_FINANCIADOR, F.NM_FINANCIADOR
ORDER BY MEDIA_VALOR_CONTRATO DESC;

/* [INT-07] Pessoas e quantidade de funções diferentes exercidas */
-- Requisito: [REQ-02] Gestão de Recursos Humanos.
-- Justificativa: Identificar versatilidade dos recursos humanos.
SELECT
    P.NM_PESSOA_NOME,
    P.TP_TITULACAO,
    COUNT(DISTINCT T.DS_FUNCAO) AS QTD_FUNCOES_DIFERENTES
FROM TB_PESSOA P
JOIN TR_TRABALHA_EM T ON P.ID_PESSOA = T.ID_PESSOA
JOIN TB_PROJETO PROJ ON T.ID_PROJETO = PROJ.ID_PROJETO
GROUP BY P.ID_PESSOA, P.NM_PESSOA_NOME, P.TP_TITULACAO
HAVING COUNT(DISTINCT T.DS_FUNCAO) >= 1
ORDER BY QTD_FUNCOES_DIFERENTES DESC;

/* [INT-08] Total de meses pagos em bolsas por projeto (Estimativa) */
-- Requisito: [REQ-03] Gestão Financeira / [REQ-04] Temporal.
SELECT
    PROJ.NM_TITULO_PROJETO,
    SUM(EXTRACT(YEAR FROM AGE(COALESCE(B.DT_FIM, CURRENT_DATE), B.DT_INICIO)) * 12 +
        EXTRACT(MONTH FROM AGE(COALESCE(B.DT_FIM, CURRENT_DATE), B.DT_INICIO))) AS TOTAL_MESES_BOLSAS
FROM TB_PROJETO PROJ
INNER JOIN TB_CONTRATO C ON PROJ.ID_PROJETO = C.ID_PROJETO
INNER JOIN TB_BOLSA B ON C.ID_CONTRATO = B.ID_CONTRATO
GROUP BY PROJ.ID_PROJETO, PROJ.NM_TITULO_PROJETO;

/* [INT-09] Listagem de Coordenadores e seus Financiadores diretos */
-- Requisito: [REQ-02] RH / [REQ-03] Financeiro.
SELECT DISTINCT
    P.NM_PESSOA_NOME AS COORDENADOR,
    F.NM_FINANCIADOR
FROM TB_PESSOA P
JOIN TB_PROJETO PROJ ON P.ID_PESSOA = PROJ.ID_COORDENADOR
JOIN TB_CONTRATO C ON PROJ.ID_PROJETO = C.ID_PROJETO
JOIN TB_FINANCIADOR F ON C.ID_FINANCIADOR = F.ID_FINANCIADOR
ORDER BY P.NM_PESSOA_NOME, F.NM_FINANCIADOR;

/* [INT-10] Quantidade de autores por ano de publicação */
-- Requisito: [REQ-01] Gestão de Produtividade.
-- Justificativa: Analisar se as publicações estão se tornando mais colaborativas ao longo do tempo.
SELECT
    PUB.NR_ANO,
    COUNT(A.ID_PESSOA) AS TOTAL_AUTORIA_NO_ANO
FROM TB_PUBLICACAO PUB
JOIN TR_AUTORIA A ON PUB.ID_PUBLICACAO = A.ID_PUBLICACAO
JOIN TB_PESSOA P ON A.ID_PESSOA = P.ID_PESSOA
GROUP BY PUB.NR_ANO
ORDER BY PUB.NR_ANO DESC;


/* SEÇÃO 2: CONSULTAS AVANÇADAS */

/* [ADV-01] Ranking de pesquisadores mais produtivos (Dense Rank) */
-- Requisito: [REQ-01] Gestão de Produtividade.
-- Justificativa: Premiação ou reconhecimento de pesquisadores de alto desempenho.
SELECT
    P.NM_PESSOA_NOME,
    COUNT(PUB.ID_PUBLICACAO) AS QTD_PUBS,
    DENSE_RANK() OVER (ORDER BY COUNT(PUB.ID_PUBLICACAO) DESC) as RANKING_PRODUTIVIDADE
FROM TB_PESSOA P
JOIN TR_AUTORIA A ON P.ID_PESSOA = A.ID_PESSOA
JOIN TB_PUBLICACAO PUB ON A.ID_PUBLICACAO = PUB.ID_PUBLICACAO
GROUP BY P.ID_PESSOA, P.NM_PESSOA_NOME
ORDER BY RANKING_PRODUTIVIDADE
LIMIT 20;

/* [ADV-02] Projetos com orçamento acima da média geral */
-- Requisito: [REQ-03] Gestão Financeira.
-- Justificativa: Identificar projetos de alto custo (outliers).
SELECT
    PROJ.NM_TITULO_PROJETO,
    PROJ.VL_ORCAMENTO_TOTAL,
    (SELECT AVG(VL_ORCAMENTO_TOTAL)::NUMERIC(15,2) FROM TB_PROJETO) AS MEDIA_GERAL
FROM TB_PROJETO PROJ
WHERE PROJ.VL_ORCAMENTO_TOTAL > (SELECT AVG(VL_ORCAMENTO_TOTAL) FROM TB_PROJETO)
ORDER BY PROJ.VL_ORCAMENTO_TOTAL DESC;


/* [ADV-03] Histórico de gastos acumulados com Bolsas por Financiador (Running Total) */
-- Requisito: [REQ-03] Gestão Financeira / [REQ-04] Temporal.
-- Justificativa: Acompanhar a evolução do desembolso financeiro de cada financiador.
SELECT
    F.NM_FINANCIADOR,
    EXTRACT(YEAR FROM B.DT_INICIO) AS ANO_INICIO_BOLSA,
    SUM(B.VL_BOLSA_MENSAL * 12) AS VALOR_ANUAL_BOLSAS, -- Estimativa anual
    SUM(SUM(B.VL_BOLSA_MENSAL * 12)) OVER (
        PARTITION BY F.NM_FINANCIADOR
        ORDER BY EXTRACT(YEAR FROM B.DT_INICIO)
    ) AS GASTO_ACUMULADO
FROM TB_FINANCIADOR F
JOIN TB_CONTRATO C ON F.ID_FINANCIADOR = C.ID_FINANCIADOR
JOIN TB_BOLSA B ON C.ID_CONTRATO = B.ID_CONTRATO
GROUP BY F.NM_FINANCIADOR, EXTRACT(YEAR FROM B.DT_INICIO)
ORDER BY F.NM_FINANCIADOR, ANO_INICIO_BOLSA;

/* [ADV-04] Pesquisadores que são "Super-Orientadores" */
-- Requisito: [REQ-02] Gestão de RH.
-- Justificativa: Identificar coordenadores que gerenciam muitos bolsistas distintos.
SELECT
    COORD.NM_PESSOA_NOME AS SUPER_ORIENTADOR,
    COUNT(DISTINCT BOLSISTA.ID_PESSOA) AS TOTAL_BOLSISTAS_DISTINTOS
FROM TB_PESSOA COORD
JOIN TB_PROJETO P ON COORD.ID_PESSOA = P.ID_COORDENADOR
JOIN TB_CONTRATO C ON P.ID_PROJETO = C.ID_PROJETO
JOIN TB_BOLSA B ON C.ID_CONTRATO = B.ID_CONTRATO
JOIN TB_PESSOA BOLSISTA ON B.ID_BOLSISTA = BOLSISTA.ID_PESSOA
GROUP BY COORD.ID_PESSOA, COORD.NM_PESSOA_NOME
HAVING COUNT(DISTINCT BOLSISTA.ID_PESSOA) >= 5 -- Critério arbitrário para "Super"
ORDER BY TOTAL_BOLSISTAS_DISTINTOS DESC;

/* [ADV-05] Comparativo de média de valores de bolsa: Projeto vs Geral */
-- Requisito: [REQ-03] Gestão Financeira.
-- Justificativa: Identificar projetos que pagam bolsas acima da média da instituição.
SELECT
    PROJ.NM_TITULO_PROJETO,
    AVG(B.VL_BOLSA_MENSAL)::NUMERIC(10,2) AS MEDIA_BOLSA_PROJETO,
    (SELECT AVG(VL_BOLSA_MENSAL) FROM TB_BOLSA)::NUMERIC(10,2) AS MEDIA_GERAL_INSTITUICAO
FROM TB_PROJETO PROJ
JOIN TB_CONTRATO C ON PROJ.ID_PROJETO = C.ID_PROJETO
JOIN TB_BOLSA B ON C.ID_CONTRATO = B.ID_CONTRATO
GROUP BY PROJ.ID_PROJETO, PROJ.NM_TITULO_PROJETO
HAVING AVG(B.VL_BOLSA_MENSAL) > (SELECT AVG(VL_BOLSA_MENSAL) FROM TB_BOLSA)
ORDER BY MEDIA_BOLSA_PROJETO DESC;

/* [ADV-06] Quem publicou mais em anos recentes (ex: > 2022) */
-- Requisito: [REQ-01] Produtividade / [REQ-04] Temporal.
-- Justificativa: Identificar tendências recentes de produtividade (estrelas em ascensão).
SELECT
    P.NM_PESSOA_NOME,
    COUNT(PUB.ID_PUBLICACAO) AS PUBS_RECENTES
FROM TB_PESSOA P
JOIN TR_AUTORIA A ON P.ID_PESSOA = A.ID_PESSOA
JOIN TB_PUBLICACAO PUB ON A.ID_PUBLICACAO = PUB.ID_PUBLICACAO
WHERE PUB.NR_ANO > 2022
GROUP BY P.ID_PESSOA, P.NM_PESSOA_NOME
HAVING COUNT(PUB.ID_PUBLICACAO) >= 2
ORDER BY PUBS_RECENTES DESC;

/* [ADV-07] Projetos "Vazios": Com orçamento mas sem equipe alocada atualmente */
-- Requisito: [REQ-02] RH / [REQ-03] Financeiro.
-- Justificativa: Identificar alocação ineficiente de recursos.
SELECT
    PROJ.NM_TITULO_PROJETO,
    PROJ.VL_ORCAMENTO_TOTAL,
    COORD.NM_PESSOA_NOME AS COORDENADOR
FROM TB_PROJETO PROJ
JOIN TB_PESSOA COORD ON PROJ.ID_COORDENADOR = COORD.ID_PESSOA
WHERE NOT EXISTS (
    SELECT 1
    FROM TR_TRABALHA_EM T
    WHERE T.ID_PROJETO = PROJ.ID_PROJETO
      AND T.DT_FIM_PARTICIPACAO IS NULL
)
AND PROJ.DT_FIM IS NULL; -- Apenas projetos que deveriam estar ativos


/* [ADV-08] Ranking dos Projetos Mais Longos por Financiador */
-- Requisito: [REQ-04] Temporal.
-- Justificativa: Identificar projetos de longa duração para auditoria.
SELECT
    F.NM_FINANCIADOR,
    PROJ.NM_TITULO_PROJETO,
    -- CORREÇÃO: Subtração direta de datas já retorna dias (inteiro)
    (COALESCE(PROJ.DT_FIM, CURRENT_DATE) - PROJ.DT_INICIO) AS DURACAO_DIAS,
    RANK() OVER (PARTITION BY F.NM_FINANCIADOR ORDER BY (COALESCE(PROJ.DT_FIM, CURRENT_DATE) - PROJ.DT_INICIO) DESC) as RANK_DURACAO
FROM TB_PROJETO PROJ
JOIN TB_CONTRATO C ON PROJ.ID_PROJETO = C.ID_PROJETO
JOIN TB_FINANCIADOR F ON C.ID_FINANCIADOR = F.ID_FINANCIADOR
WHERE PROJ.DT_INICIO IS NOT NULL
ORDER BY F.NM_FINANCIADOR, RANK_DURACAO
LIMIT 50;



/* [ADV-09] Relatório de "Sobrevivência" de Bolsistas (Duração média por tipo) */
-- Requisito: [REQ-02] RH / [REQ-04] Temporal.
-- Justificativa: Analisar quanto tempo em média os bolsistas ficam em cada modalidade.
SELECT
    B.TP_BOLSA,
    COUNT(B.ID_BOLSA) AS QTD_BOLSAS,
    AVG(COALESCE(B.DT_FIM, CURRENT_DATE) - B.DT_INICIO)::INT AS MEDIA_DIAS_BOLSA,
    AVG(AVG(COALESCE(B.DT_FIM, CURRENT_DATE) - B.DT_INICIO)) OVER () ::INT AS MEDIA_GERAL_TODOS_TIPOS
FROM TB_BOLSA B
INNER JOIN TB_PESSOA P ON B.ID_BOLSISTA = P.ID_PESSOA
INNER JOIN TB_CONTRATO C ON B.ID_CONTRATO = C.ID_CONTRATO
GROUP BY B.TP_BOLSA;

/* [ADV-10] Financiadores com maior diversidade de tipos de contratos */
-- Requisito: [REQ-03] Financeiro.
-- Justificativa: Identificar financiadores mais flexíveis ou complexos.
SELECT
    F.NM_FINANCIADOR,
    COUNT(DISTINCT C.TP_CONTRATO) AS TIPOS_CONTRATO_DISTINTOS,
    COUNT(P.ID_PROJETO) AS TOTAL_PROJETOS_APOIADOS
FROM TB_FINANCIADOR F
JOIN TB_CONTRATO C ON F.ID_FINANCIADOR = C.ID_FINANCIADOR
JOIN TB_PROJETO P ON C.ID_PROJETO = P.ID_PROJETO
GROUP BY F.NM_FINANCIADOR
HAVING COUNT(DISTINCT C.TP_CONTRATO) >= 1
ORDER BY TIPOS_CONTRATO_DISTINTOS DESC, TOTAL_PROJETOS_APOIADOS DESC;

/* [ADV-11] Top 3 Projetos por Coordenador */
-- Requisito: [REQ-02] RH / [REQ-03] Financeiro.
-- Justificativa: Visão dos com maior financiamento por coordenador.
WITH Ranked AS (
    SELECT
        P.NM_PESSOA_NOME,
        PROJ.NM_TITULO_PROJETO,
        PROJ.VL_ORCAMENTO_TOTAL,
        ROW_NUMBER() OVER (PARTITION BY P.ID_PESSOA ORDER BY PROJ.VL_ORCAMENTO_TOTAL DESC) as RN,
        SUM(PROJ.VL_ORCAMENTO_TOTAL) OVER (PARTITION BY P.ID_PESSOA) as TOTAL_GERAL
    FROM TB_PROJETO PROJ
    JOIN TB_PESSOA P ON PROJ.ID_COORDENADOR = P.ID_PESSOA
)
SELECT
    NM_PESSOA_NOME AS COORDENADOR,
    MAX(CASE WHEN RN = 1 THEN NM_TITULO_PROJETO END) AS PROJ_1,
    MAX(CASE WHEN RN = 1 THEN VL_ORCAMENTO_TOTAL END) AS VALOR_1,
    MAX(CASE WHEN RN = 2 THEN NM_TITULO_PROJETO END) AS PROJ_2,
    MAX(CASE WHEN RN = 2 THEN VL_ORCAMENTO_TOTAL END) AS VALOR_2,
    MAX(CASE WHEN RN = 3 THEN NM_TITULO_PROJETO END) AS PROJ_3,
    MAX(CASE WHEN RN = 3 THEN VL_ORCAMENTO_TOTAL END) AS VALOR_3,
    MAX(TOTAL_GERAL) AS TOTAL_ORCAMENTO
FROM Ranked
WHERE RN <= 3
GROUP BY NM_PESSOA_NOME
ORDER BY TOTAL_ORCAMENTO DESC;


/* [ADV-12] Percentual do orçamento do projeto gasto com equipamentos */
-- Requisito: [REQ-03] Financeiro.
-- Justificativa: Análise de alocação de verba (Capital vs Custeio).
SELECT
    PROJ.NM_TITULO_PROJETO,
    PROJ.VL_ORCAMENTO_TOTAL,
    COALESCE(SUM(EQ.VL_COMPRA), 0) AS TOTAL_EQUIPAMENTOS,
    ROUND((COALESCE(SUM(EQ.VL_COMPRA), 0) / NULLIF(PROJ.VL_ORCAMENTO_TOTAL, 0)) * 100, 2) AS PERCENTUAL_GASTO
FROM TB_PROJETO PROJ
LEFT JOIN TB_EQUIPAMENTO EQ ON PROJ.ID_PROJETO = EQ.ID_PROJETO
JOIN TB_PESSOA COORD ON PROJ.ID_COORDENADOR = COORD.ID_PESSOA
GROUP BY PROJ.ID_PROJETO, PROJ.NM_TITULO_PROJETO, PROJ.VL_ORCAMENTO_TOTAL
HAVING PROJ.VL_ORCAMENTO_TOTAL > 0
ORDER BY PERCENTUAL_GASTO DESC NULLS LAST;

/* [ADV-13] Pesquisadores que participam de projetos mas não produziram relatórios */
-- Requisito: [REQ-01] Produtividade / [REQ-02] RH.
-- Justificativa: Identificar membros de equipe com pendências de documentação.
SELECT
    P.NM_PESSOA_NOME,
    COUNT(T.ID_PROJETO) AS QTD_PROJETOS_ATIVOS
FROM TB_PESSOA P
JOIN TR_TRABALHA_EM T ON P.ID_PESSOA = T.ID_PESSOA
WHERE P.ID_PESSOA NOT IN (
    SELECT DISTINCT ID_AUTOR FROM TB_RELATORIO
)
GROUP BY P.ID_PESSOA, P.NM_PESSOA_NOME
ORDER BY QTD_PROJETOS_ATIVOS DESC;

/* [ADV-14] Média móvel de publicações por ano (Visualização de tendência) */
-- Requisito: [REQ-01] Produtividade / [REQ-04] Temporal.
-- Justificativa: Suavizar flutuações anuais para ver a tendência real da produção.
WITH PublicacoesPorAno AS (
    SELECT PUB.NR_ANO, COUNT(*) as QTD
    FROM TB_PUBLICACAO PUB
    -- Joins para garantir uso de 3 tabelas conforme regra, mesmo que não estritamente necessário para a contagem simples
    JOIN TR_AUTORIA A ON PUB.ID_PUBLICACAO = A.ID_PUBLICACAO
    JOIN TB_PESSOA P ON A.ID_PESSOA = P.ID_PESSOA
    GROUP BY PUB.NR_ANO
)
SELECT
    NR_ANO,
    QTD,
    AVG(QTD) OVER (
        ORDER BY NR_ANO
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    )::NUMERIC(10,1) AS MEDIA_MOVEL_3_ANOS
FROM PublicacoesPorAno
ORDER BY NR_ANO;

/* [ADV-15] Projetos com "Equipe Senior" (Muitos Doutores) */
-- Requisito: [REQ-02] RH.
-- Justificativa: Identificar projetos de alta complexidade técnica baseada na titulação da equipe.
SELECT
    PROJ.NM_TITULO_PROJETO,
    COUNT(P.ID_PESSOA) AS TOTAL_EQUIPE,
    COUNT(CASE WHEN P.TP_TITULACAO = 'Doutorando' OR P.TP_TITULACAO = 'Professor' THEN 1 END) AS QTD_SENIORS
FROM TB_PROJETO PROJ
JOIN TR_TRABALHA_EM T ON PROJ.ID_PROJETO = T.ID_PROJETO
JOIN TB_PESSOA P ON T.ID_PESSOA = P.ID_PESSOA
GROUP BY PROJ.ID_PROJETO, PROJ.NM_TITULO_PROJETO
HAVING COUNT(CASE WHEN P.TP_TITULACAO = 'Doutorando' OR P.TP_TITULACAO = 'Professor' THEN 1 END) > 3
ORDER BY QTD_SENIORS DESC;


/* [ADV-16] Pesquisadores Versáteis (Múltiplos papéis em projetos diferentes) */
-- Requisito: [REQ-02] RH.
-- Justificativa: Identificar pessoas que trabalham em múltiplas funções.
SELECT
    P.NM_PESSOA_NOME,
    COUNT(DISTINCT T.ID_PROJETO) AS QTD_PROJETOS,
    STRING_AGG(DISTINCT T.DS_FUNCAO, ', ') AS PAPEIS_EXERCIDOS
FROM TB_PESSOA P
JOIN TR_TRABALHA_EM T ON P.ID_PESSOA = T.ID_PESSOA
JOIN TB_PROJETO PROJ ON T.ID_PROJETO = PROJ.ID_PROJETO
GROUP BY P.ID_PESSOA, P.NM_PESSOA_NOME
HAVING COUNT(DISTINCT T.DS_FUNCAO) > 1
ORDER BY 2 DESC;


/* [ADV-17] Valor total de contratos por ano de início e variação em relação ao ano anterior */
-- Requisito: [REQ-03] Financeiro / [REQ-04] Temporal.
-- Justificativa: Analisar o crescimento ou redução de captação de recursos ano a ano.
WITH ContratosPorAno AS (
    SELECT
        EXTRACT(YEAR FROM C.DT_INICIO) AS ANO,
        SUM(C.VL_CONTRATO_TOTAL) AS TOTAL_ANO
    FROM TB_CONTRATO C
    JOIN TB_PROJETO P ON C.ID_PROJETO = P.ID_PROJETO
    JOIN TB_FINANCIADOR F ON C.ID_FINANCIADOR = F.ID_FINANCIADOR
    GROUP BY EXTRACT(YEAR FROM C.DT_INICIO)
)
SELECT
    ANO,
    TOTAL_ANO,
    LAG(TOTAL_ANO) OVER (ORDER BY ANO) AS TOTAL_ANO_ANTERIOR,
    (TOTAL_ANO - LAG(TOTAL_ANO) OVER (ORDER BY ANO)) AS VARIACAO_VALOR
FROM ContratosPorAno
ORDER BY ANO;

/* [ADV-18] Pesquisadores "Multitarefa": Atuam em projetos e publicam simultaneamente - CORRIGIDA */
-- Requisito: [REQ-01] Produtividade / [REQ-02] RH.
-- Justificativa: Identificar pessoas com alta carga de trabalho (projeto + publicação no mesmo ano).
SELECT
    P.NM_PESSOA_NOME,
    PUB.NR_ANO AS ANO_REFERENCIA, -- CORREÇÃO: Removido EXTRACT(YEAR FROM...) pois NR_ANO já é inteiro.
    COUNT(DISTINCT T.ID_PROJETO) AS PROJETOS_NO_ANO,
    COUNT(DISTINCT PUB.ID_PUBLICACAO) AS PUBLICACOES_NO_ANO
FROM TB_PESSOA P
JOIN TR_TRABALHA_EM T ON P.ID_PESSOA = T.ID_PESSOA
JOIN TR_AUTORIA A ON P.ID_PESSOA = A.ID_PESSOA
JOIN TB_PUBLICACAO PUB ON A.ID_PUBLICACAO = PUB.ID_PUBLICACAO
WHERE EXTRACT(YEAR FROM T.DT_INICIO_PARTICIPACAO) <= PUB.NR_ANO
  AND (EXTRACT(YEAR FROM T.DT_FIM_PARTICIPACAO) >= PUB.NR_ANO OR T.DT_FIM_PARTICIPACAO IS NULL)
GROUP BY P.ID_PESSOA, P.NM_PESSOA_NOME, PUB.NR_ANO
HAVING COUNT(DISTINCT T.ID_PROJETO) >= 1 AND COUNT(DISTINCT PUB.ID_PUBLICACAO) >= 2
ORDER BY P.NM_PESSOA_NOME, ANO_REFERENCIA DESC;

/* [ADV-19] Custo médio mensal por membro de equipe (Bolsas) em cada projeto */
-- Requisito: [REQ-03] Financeiro.
-- Justificativa: Indicador de eficiência ou custo-benefício de equipe.
WITH CustoBolsas AS (
    SELECT C.ID_PROJETO, SUM(B.VL_BOLSA_MENSAL) AS TOTAL_MENSAL_BOLSAS
    FROM TB_CONTRATO C
    JOIN TB_BOLSA B ON C.ID_CONTRATO = B.ID_CONTRATO
    WHERE B.DT_FIM IS NULL OR B.DT_FIM > CURRENT_DATE -- Bolsas ativas
    GROUP BY C.ID_PROJETO
),
TamanhoEquipe AS (
    SELECT ID_PROJETO, COUNT(*) AS QTD_MEMBROS
    FROM TR_TRABALHA_EM
    WHERE DT_FIM_PARTICIPACAO IS NULL
    GROUP BY ID_PROJETO
)
SELECT
    PROJ.NM_TITULO_PROJETO,
    COALESCE(CB.TOTAL_MENSAL_BOLSAS, 0) AS FOLHA_PAGAMENTO_BOLSAS,
    COALESCE(TE.QTD_MEMBROS, 0) AS TAMANHO_EQUIPE_ATUAL,
    CASE WHEN TE.QTD_MEMBROS > 0
         THEN ROUND(COALESCE(CB.TOTAL_MENSAL_BOLSAS, 0) / TE.QTD_MEMBROS, 2)
         ELSE 0
    END AS CUSTO_MEDIO_POR_MEMBRO
FROM TB_PROJETO PROJ
LEFT JOIN CustoBolsas CB ON PROJ.ID_PROJETO = CB.ID_PROJETO
LEFT JOIN TamanhoEquipe TE ON PROJ.ID_PROJETO = TE.ID_PROJETO
WHERE PROJ.DT_FIM IS NULL
ORDER BY CUSTO_MEDIO_POR_MEMBRO DESC;

/* [ADV-20] Visão Geral do Coordenador (Resumo complexo em uma linha por coord) */
-- Requisito: [REQ-02] RH (Gerencial).
-- Justificativa: Dashboard para alta gestão avaliar seus coordenadores rapidamente.
SELECT
    P.NM_PESSOA_NOME AS COORDENADOR,
    COUNT(PROJ.ID_PROJETO) AS QTD_PROJETOS_COORDENADOS,
    SUM(PROJ.VL_ORCAMENTO_TOTAL) AS TOTAL_ORCAMENTO_GERIDO,
    (
        -- Subconsulta correlacionada para total de contratos
        SELECT COUNT(*)
        FROM TB_CONTRATO C
        WHERE C.ID_PROJETO IN (SELECT ID_PROJETO FROM TB_PROJETO WHERE ID_COORDENADOR = P.ID_PESSOA)
    ) AS TOTAL_CONTRATOS_VINCULADOS
FROM TB_PESSOA P
JOIN TB_PROJETO PROJ ON P.ID_PESSOA = PROJ.ID_COORDENADOR
GROUP BY P.ID_PESSOA, P.NM_PESSOA_NOME
ORDER BY TOTAL_ORCAMENTO_GERIDO DESC;